// Generated by gencpp from file frogs_msgs/robot_armFeedback.msg
// DO NOT EDIT!


#ifndef FROGS_MSGS_MESSAGE_ROBOT_ARMFEEDBACK_H
#define FROGS_MSGS_MESSAGE_ROBOT_ARMFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace frogs_msgs
{
template <class ContainerAllocator>
struct robot_armFeedback_
{
  typedef robot_armFeedback_<ContainerAllocator> Type;

  robot_armFeedback_()
    : percentage(0.0)  {
    }
  robot_armFeedback_(const ContainerAllocator& _alloc)
    : percentage(0.0)  {
  (void)_alloc;
    }



   typedef double _percentage_type;
  _percentage_type percentage;





  typedef boost::shared_ptr< ::frogs_msgs::robot_armFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::frogs_msgs::robot_armFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct robot_armFeedback_

typedef ::frogs_msgs::robot_armFeedback_<std::allocator<void> > robot_armFeedback;

typedef boost::shared_ptr< ::frogs_msgs::robot_armFeedback > robot_armFeedbackPtr;
typedef boost::shared_ptr< ::frogs_msgs::robot_armFeedback const> robot_armFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::frogs_msgs::robot_armFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::frogs_msgs::robot_armFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace frogs_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'frogs_msgs': ['/home/ros/catkin_ws/devel/share/frogs_msgs/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::frogs_msgs::robot_armFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::frogs_msgs::robot_armFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::frogs_msgs::robot_armFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::frogs_msgs::robot_armFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::frogs_msgs::robot_armFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::frogs_msgs::robot_armFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::frogs_msgs::robot_armFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "46302a97c06fe5a4416c427fe6ee8804";
  }

  static const char* value(const ::frogs_msgs::robot_armFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x46302a97c06fe5a4ULL;
  static const uint64_t static_value2 = 0x416c427fe6ee8804ULL;
};

template<class ContainerAllocator>
struct DataType< ::frogs_msgs::robot_armFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "frogs_msgs/robot_armFeedback";
  }

  static const char* value(const ::frogs_msgs::robot_armFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::frogs_msgs::robot_armFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#feedback\n\
float64 percentage\n\
\n\
\n\
";
  }

  static const char* value(const ::frogs_msgs::robot_armFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::frogs_msgs::robot_armFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.percentage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_armFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::frogs_msgs::robot_armFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::frogs_msgs::robot_armFeedback_<ContainerAllocator>& v)
  {
    s << indent << "percentage: ";
    Printer<double>::stream(s, indent + "  ", v.percentage);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FROGS_MSGS_MESSAGE_ROBOT_ARMFEEDBACK_H
