(cl:defpackage frogs_msgs-msg
  (:use )
  (:export
   "<ROBOT_ARMACTION>"
   "ROBOT_ARMACTION"
   "<ROBOT_ARMACTIONFEEDBACK>"
   "ROBOT_ARMACTIONFEEDBACK"
   "<ROBOT_ARMACTIONGOAL>"
   "ROBOT_ARMACTIONGOAL"
   "<ROBOT_ARMACTIONRESULT>"
   "ROBOT_ARMACTIONRESULT"
   "<ROBOT_ARMFEEDBACK>"
   "ROBOT_ARMFEEDBACK"
   "<ROBOT_ARMGOAL>"
   "ROBOT_ARMGOAL"
   "<ROBOT_ARMRESULT>"
   "ROBOT_ARMRESULT"
  ))

