; Auto-generated. Do not edit!


(cl:in-package frogs_msgs-msg)


;//! \htmlinclude robot_armResult.msg.html

(cl:defclass <robot_armResult> (roslisp-msg-protocol:ros-message)
  ((count
    :reader count
    :initarg :count
    :type cl:integer
    :initform 0))
)

(cl:defclass robot_armResult (<robot_armResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <robot_armResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'robot_armResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name frogs_msgs-msg:<robot_armResult> is deprecated: use frogs_msgs-msg:robot_armResult instead.")))

(cl:ensure-generic-function 'count-val :lambda-list '(m))
(cl:defmethod count-val ((m <robot_armResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader frogs_msgs-msg:count-val is deprecated.  Use frogs_msgs-msg:count instead.")
  (count m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <robot_armResult>) ostream)
  "Serializes a message object of type '<robot_armResult>"
  (cl:let* ((signed (cl:slot-value msg 'count)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <robot_armResult>) istream)
  "Deserializes a message object of type '<robot_armResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'count) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<robot_armResult>)))
  "Returns string type for a message object of type '<robot_armResult>"
  "frogs_msgs/robot_armResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'robot_armResult)))
  "Returns string type for a message object of type 'robot_armResult"
  "frogs_msgs/robot_armResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<robot_armResult>)))
  "Returns md5sum for a message object of type '<robot_armResult>"
  "8dbac33d2eb67bfeeedd516d65fec846")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'robot_armResult)))
  "Returns md5sum for a message object of type 'robot_armResult"
  "8dbac33d2eb67bfeeedd516d65fec846")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<robot_armResult>)))
  "Returns full string definition for message of type '<robot_armResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%int64 count~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'robot_armResult)))
  "Returns full string definition for message of type 'robot_armResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%int64 count~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <robot_armResult>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <robot_armResult>))
  "Converts a ROS message object to a list"
  (cl:list 'robot_armResult
    (cl:cons ':count (count msg))
))
