; Auto-generated. Do not edit!


(cl:in-package frogs_msgs-msg)


;//! \htmlinclude robot_armFeedback.msg.html

(cl:defclass <robot_armFeedback> (roslisp-msg-protocol:ros-message)
  ((percentage
    :reader percentage
    :initarg :percentage
    :type cl:float
    :initform 0.0))
)

(cl:defclass robot_armFeedback (<robot_armFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <robot_armFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'robot_armFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name frogs_msgs-msg:<robot_armFeedback> is deprecated: use frogs_msgs-msg:robot_armFeedback instead.")))

(cl:ensure-generic-function 'percentage-val :lambda-list '(m))
(cl:defmethod percentage-val ((m <robot_armFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader frogs_msgs-msg:percentage-val is deprecated.  Use frogs_msgs-msg:percentage instead.")
  (percentage m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <robot_armFeedback>) ostream)
  "Serializes a message object of type '<robot_armFeedback>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'percentage))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <robot_armFeedback>) istream)
  "Deserializes a message object of type '<robot_armFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'percentage) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<robot_armFeedback>)))
  "Returns string type for a message object of type '<robot_armFeedback>"
  "frogs_msgs/robot_armFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'robot_armFeedback)))
  "Returns string type for a message object of type 'robot_armFeedback"
  "frogs_msgs/robot_armFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<robot_armFeedback>)))
  "Returns md5sum for a message object of type '<robot_armFeedback>"
  "46302a97c06fe5a4416c427fe6ee8804")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'robot_armFeedback)))
  "Returns md5sum for a message object of type 'robot_armFeedback"
  "46302a97c06fe5a4416c427fe6ee8804")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<robot_armFeedback>)))
  "Returns full string definition for message of type '<robot_armFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float64 percentage~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'robot_armFeedback)))
  "Returns full string definition for message of type 'robot_armFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float64 percentage~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <robot_armFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <robot_armFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'robot_armFeedback
    (cl:cons ':percentage (percentage msg))
))
